In [6]:
import numpy as np
import pandas as pd

In [7]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

df = pd.DataFrame(data, columns=columns)

In [10]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [11]:
df.head(2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [14]:
df[['Engine Cylinders','Year']]

   Engine Cylinders  Year
0                 4  1991
1                 4  2017
2                 4  2010
3                 4  2017
4                 6  2017

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [19]:
df.Year * 2

0    3982
1    4034
2    4020
3    4034
4    4034
Name: Year, dtype: int64

In [20]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [22]:
df[df.Year < 2000]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [23]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [24]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [28]:
df.shape

(5, 8)

In [29]:
pd.__version__

'3.0.6'

In [31]:
df = pd.read_csv('./car_fuel_efficiency_2026.csv')

In [34]:
df.shape

(10000, 11)

In [35]:
df.head(2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [38]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [43]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [45]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [46]:
df.isna().sum() > 0

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

In [55]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.describe()

count    2994.000000
mean       30.741015
std         2.835474
min        21.300000
25%        28.700000
50%        30.700000
75%        32.500000
max        41.200000
Name: fuel_efficiency_mpg, dtype: float64

In [57]:
df.horsepower.median()

np.float64(254.0)

In [72]:
df.groupby(df.horsepower).horsepower.count().sort_values(ascending=False)

horsepower
252.0    174
246.0    168
256.0    168
253.0    165
259.0    165
        ...
320.0      1
322.0      1
327.0      1
328.0      1
330.0      1
Name: horsepower, Length: 153, dtype: int64

In [78]:
df.groupby('horsepower').horsepower.count().sort_values(ascending=False)

horsepower
252.0    174
246.0    168
256.0    168
253.0    165
259.0    165
        ...
320.0      1
322.0      1
327.0      1
328.0      1
330.0      1
Name: horsepower, Length: 153, dtype: int64

In [81]:
df.horsepower.value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [80]:
df.horsepower.fillna(252.0).median()

np.float64(252.0)

In [87]:
X = df[df.origin == 'Asia'][['vehicle_weight', 'model_year']].head(7).values

In [102]:
XTX = X.T.dot(X)

In [103]:
XTX_inv = np.linalg.inv(XTX)

In [105]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [112]:
w = XTX_inv.dot(X.T).dot(y)

In [116]:
w.sum().round(3)

np.float64(0.369)